### ISSUE TITLE
PostgresqlConnectionManager create connection from NpgsqlDatasource

### ISSUE THREAD

**Issue by scrocquesel-ml150** [DbUp/dbup-postgresql#12]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Description

Npgsql allows to configure the connection settings by code. For example, provide the password at connection time with help of [password provider or periodic password rotation](https://www.npgsql.org/doc/security.html#auth-token-rotation-and-dynamic-password) on the NpgsqlDatasource.

PostgresqlConnectionManager should take a NpgsqlDatasource and create connection from it.

```
public PostgresqlConnectionManager(NpgsqlDataSource datasource)
    : base(new DelegateConnectionFactory(l => datasource.OpenConnection()))
{
}
```

### What is the impact?

NpgsqlDatasource has been introduced in a more recent Npgsql version than the one currently used and it doesn't target `netstandard1.3`.

**Comment by droyad** [comment]
Implemented via #14
