### ISSUE TITLE
Npgsql version should be upgraded

### ISSUE THREAD

**Issue by toizo** [DbUp/dbup-postgresql#13]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Description

I see that currently, this package uses [Npgsql v3.2.7](https://github.com/npgsql/npgsql/releases/tag/v3.2.7), that was released in 2018. This is a version that is out of support and therefore I believe it should be updated to at least v6, if not the latest (v8). 

### What is the impact?

Apart from possible security issues, there are some breaking changes, e.g. we could not use VerifyFull SSL mode in our connection string.

**Comment by toizo** [comment]
I checked out this repo and see that it's probably due to your support of `netstandard1.3`. I also noticed that it is planned to be dropped in the next major release, so the upgrade will be possible. I will stay tuned.

**Comment by droyad** [comment]
Fixed by #17
