### ISSUE TITLE
Support setting a custom CertificateValidationCallback on database connections

### ISSUE THREAD

**Issue by MarkOtter** [DbUp/dbup-postgresql#23]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Description

I've created a PR for this, but didn't write an issue yet. Not sure how to link the issue to the PR?

Because of company policies we need to support SSL/TLS connections with certificates of which the root CA is not in the certificate store of the OS. Luckily, .NET supports adding custom certificate validation callback methods to connection 'objects', like httpclient and dbconnection.

We'd like to add this option to the `dbup-postgress` package as well. In the extension methods, I'd suggest adding overloads to supply such method which will be passed to the Postgres Connection instance.

### What is the impact?

This change will add functionality which does not break any existing behaviour or APIs.
Though this is a not so common use case, the added value is big for the consumers requiring this.
Our current solution is to copy/past parts of the code of this package and alter it in our codebase, which makes upgrading of the NuGet package brittle.

**Comment by droyad** [comment]
Thanks @MarkOtter
