### ISSUE TITLE
Need an API to Ensure schema exists in postgressql

### ISSUE THREAD

**Issue by hari2m** [DbUp/dbup-postgresql#7]
When working with Postgresql. I am using docker instance as I develop locally to spin up and test my code, in this case I am using ensure database so that it creates the database when I spin up new docker container. But the code fails as the schema does not exist and I have to create a schema manually. It would help if we have a ensure schema API.

**Comment by droyad** [comment]
This is covered by https://github.com/DbUp/DbUp/issues/728
